import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './style.css';

const API = 'http://localhost:8080/api';
function App() {
  const conversationId = sessionStorage.getItem('studyConversationId') || crypto.randomUUID();
  sessionStorage.setItem('studyConversationId', conversationId);
  const [messages, setMessages] = useState([{ role: 'ai', text: 'Hi! Ask me to explain a concept, make a quiz, or create a study plan.' }]);
  const [input, setInput] = useState(''); const [approvals, setApprovals] = useState([]); const [busy, setBusy] = useState(false); const [notice, setNotice] = useState('');
  const loadApprovals = () => fetch(`${API}/approvals/pending`).then(async r => { if (!r.ok) throw new Error('Could not load approvals.'); return r.json(); }).then(setApprovals).catch(() => setNotice('Could not load pending approvals.'));
  useEffect(() => { loadApprovals(); }, []);
  const send = async (event) => { event.preventDefault(); if (!input.trim() || busy) return; const message = input.trim(); setInput(''); setMessages(m => [...m, { role: 'student', text: message }]); setBusy(true); try { const response = await fetch(`${API}/chat`, { method: 'POST', headers: {'Content-Type':'application/json'}, body: JSON.stringify({message, conversationId}) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'The request failed.'); setMessages(m => [...m, { role:'ai', text: data.response }]); loadApprovals(); } catch (error) { setMessages(m => [...m, { role:'ai', text: error.message || 'The backend is not running yet. Start Spring Boot and try again.' }]); } finally { setBusy(false); } };
  const decide = async (id, action) => { const response = await fetch(`${API}/approvals/${id}/${action}`, {method:'POST'}); const data = await response.json(); if (!response.ok) { setNotice(data.error || 'The approval could not be processed.'); return; } setNotice(action === 'approve' ? 'Approved successfully.' : 'Action rejected.'); loadApprovals(); };
  return <main><header><div className="eyebrow">STUDY COMPANION / 01</div><h1>AI Student<br/><em>Study Assistant</em></h1><p className="intro">A calm place to understand hard topics, practice deliberately, and turn good intentions into a plan.</p></header><section className="workspace"><div className="chat panel"><div className="panel-title"><span>Conversation</span><span className="live">● ready</span></div><div className="messages">{messages.map((m,i)=><div className={`message ${m.role}`} key={i}><span>{m.role === 'ai' ? 'AI' : 'YOU'}</span><p>{m.text}</p></div>)}</div><form onSubmit={send}><input value={input} onChange={e=>setInput(e.target.value)} placeholder="Ask anything about your studies..."/><button disabled={busy}>{busy ? '...' : 'Send'}</button></form></div><aside className="panel approvals"><div className="panel-title"><span>Pending approvals</span><span className="count">{approvals.length}</span></div>{notice && <div className="notice">{notice}</div>}{approvals.length === 0 ? <div className="empty">No decisions waiting. Ask the assistant to save a quiz or plan.</div> : approvals.map(a=><article className="approval" key={a.id}><div className="approval-tag">{a.actionType.replaceAll('_',' ')}</div><h2>{a.description}</h2><p>{a.payload}</p><div className="actions"><button onClick={()=>decide(a.id,'approve')}>Approve</button><button className="reject" onClick={()=>decide(a.id,'reject')}>Reject</button></div></article>)}</aside></section></main>
}
createRoot(document.getElementById('root')).render(<App />);
